export const INDUSTRY_OPTIONS = [
	"HVAC",
	"Plumbing",
	"Electrical services",
	"Roofing",
	"Landscaping",
	"Pest control",
	"Restoration services",
	"Fire and life safety",
	"Commercial cleaning",
	"Facilities maintenance",
	"Property management",
	"Commercial services",
	"Home services",
	"Business services",
	"IT services and MSPs",
	"Cybersecurity services",
	"Healthcare services",
	"Dental services",
	"Veterinary services",
	"Distribution",
	"Wholesale distribution",
	"Logistics and transportation",
	"Specialty manufacturing",
	"Light manufacturing",
	"Food manufacturing",
	"Industrial services",
	"Environmental services",
	"Testing and inspection",
	"Staffing and recruiting",
	"Accounting and bookkeeping",
] as const;

export const GEOGRAPHY_OPTIONS = [
	"United States",
	"Canada",
	"Texas",
	"Florida",
	"California",
	"Georgia",
	"North Carolina",
	"South Carolina",
	"Tennessee",
	"Arizona",
	"Colorado",
	"Midwest",
	"Southeast",
	"Northeast",
	"Southwest",
	"Mountain West",
	"West Coast",
	"Great Lakes",
	"Mid-Atlantic",
	"New England",
	"Pacific Northwest",
	"Dallas–Fort Worth",
	"Houston",
	"Austin",
	"San Antonio",
	"Atlanta",
	"Charlotte",
	"Nashville",
	"Tampa Bay",
	"Miami–Fort Lauderdale",
	"Phoenix",
	"Denver",
	"Chicago",
	"Minneapolis–Saint Paul",
	"Remote-friendly",
] as const;

export const EXCLUDED_CATEGORY_OPTIONS = [
	"Restaurants",
	"Bars and nightlife",
	"Hospitality",
	"Retail",
	"E-commerce",
	"Pre-revenue",
	"Startups",
	"Franchises",
	"Highly seasonal",
	"Project-based revenue",
	"High customer concentration",
	"Owner-dependent",
	"Turnarounds",
	"Distressed businesses",
	"Regulated industries",
	"Cannabis",
	"Gambling",
	"Adult entertainment",
	"Cryptocurrency",
	"Real estate development",
	"General contractors",
	"Commodity businesses",
	"Declining industries",
	"Capital-intensive",
	"Government-dependent",
] as const;
